(init-package "org")
(init-package "org-bullets")
(init-package "org-wiki")
(init-package "markdown-mode")
(init-package "markdown-preview-mode")
(init-package "dockerfile-mode")
(init-package "nxml-mode")

(add-hook 'text-mode-hook 'linum-mode)
(add-hook 'text-mode-hook 'hl-line-mode)
